version: "3"

services:
    users-api:
        image: william0503/users-api
        ports:
            - "3000:3000"
        restart: "always"
        networks:
            - appPet
    
    providers-api:
        image: william0503/providers-api
        ports:
            - "3001:3001"
        restart: "always"
        networks:
            - appPet
    frontend:
        image: william0503/superapppet-frontend
        ports:
            - "3030:80"
        restart: "always"
        environment:
            - FIAP:UserAddress=http://users-api:3000/api/users/
            - FIAP:ProviderAddress=http://providers-api:3001/api/providers/
        networks:
            - appPet
        
networks: 
    appPet:
